name: flutrack-backend
dependencies:
  - python
  - requests
  - wheel
  - django
  - gunicorn
  - pip:
    - tweepy
    - requests-oauthlib
    - requests
    - oauthlib
    - djangorestframework
    - dj-database-url
    - psycopg2
    - whitenoise
    - pymongo
    - xlrd