name: flutrack-backend
dependencies:
  - mkl
  - pycosat
  - python
  - requests
  - wheel
  - django
  - pip:
    - tweepy
    - virtualenv
    - gunicorn
    - requests-oauthlib
    - requests
    - oauthlib
    - djangorestframework
    - dj-database-url
    - psycopg2
    - whitenoise