name: flutrack-backend
dependencies:
  - mkl
  - numpy
  - pip
  - pycosat
  - python
  - pyyaml
  - requests
  - nltk
  - setuptools
  - wheel
  - django
  - pip:
    - tweepy
    - virtualenv
    - gunicorn
    - requests-oauthlib
    - requests
    - oauthlib
    - djangorestframework